
###
@host = http://localhost:3001/api
@email = owner@gmail.com
@password = 123456
@token = {{token}}
###

### POST Register New User
POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
  "email": "testing@gmail.com",
  "password": "localhost"
}

### POST Login / Get Access Token
POST {{host}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

> {%
    //assert status code
    client.test("test login", () => {
        client.assert(response.status === 200, "can't register new user")
        client.assert(response.body.code === 200, "response code is not 200")
        client.assert(response.body.message === "login successfully", "response message is not 'login successful'")
    })
    client.global.set("token", "Bearer " + response.body.data.access_token)
%}


### GET My Profile
GET {{host}}/me HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

> {%
    client.test("test", () => {
        client.assert(response.status === 200, "can't get my")
        client.assert(response.body.code === 200, "response code is not 200")
        client.assert(response.body.message === "Success", "response message is not 'Success'")
    })
%}


### GET Products
GET {{host}}/products HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

> {%
    client.test("test", () => {
        client.assert(response.status === 200, "code not 200")
        client.assert(response.body.code === 200, "response code is not 200")
        client.assert(response.body.message === "Success", "response message is not 'Success'")
    })
    client.global.set("product_id_1", response.body.data[0].id)
%}

### GET Product Details
GET {{host}}/products/{{product_id_1}} HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

> {%
    client.test("test", () => {
        client.assert(response.status === 200, "code not 200")
        client.assert(response.body.code === 200, "response code is not 200")
        client.assert(response.body.message === "Success", "response message is not 'Success'")
    })
    client.global.set("shop_id_1", response.body.data.shop_id)
    client.global.set("product_id_1_stock", response.body.data.stock)
%}

### GET My Order
GET {{host}}/orders HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

> {%
    client.test("test", () => {
        client.assert(response.status === 200, "code not 200")
        client.assert(response.body.code === 200, "response code is not 200")
        client.assert(response.body.message === "fetch my orders", "response message is not 'fetch my orders'")
    })
%}

### POST Checkout / Create Order
POST {{host}}/orders/checkout HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "shop_id": {{shop_id_1}},
  "shipping_address": "Yogyakarta",
  "details": [
    {
      "product_id": {{product_id_1}},
      "quantity": 1
    }
  ]
}

> {%
    //assert status code
    client.test("test", () => {
        client.assert(response.status === 201, "code not 201")
        client.assert(response.body.code === 201, "response code is not 201")
        client.assert(response.body.message === "order created", "response message is not 'order created'")
    })
    client.global.set("order_id", response.body.data.id)
    client.global.set("order_amount", response.body.data.amount)
%}

### POST Payment Order / Create Payment
POST {{host}}/orders/payment HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "order_id": {{order_id}},
  "payment_method": "transfer",
  "amount": {{order_amount}}
}

> {%
    client.test("test", () => {
        client.assert(response.status === 201, "code not 201")
        client.assert(response.body.code === 201, "response code is not 201")
        client.assert(response.body.message === "payment order created", "response message is not 'payment order created'")
    })
%}

### GET Show My Warehouse
GET {{host}}/warehouses HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

> {%
    client.test("test", () => {
        client.assert(response.status === 200, "code not 200")
        client.assert(response.body.code === 200, "response code is not 200")
        client.assert(response.body.message === "Success", "response message is not 'Success'")

    })
    let whs = []
    let pID = parseInt(client.global.get('product_id_1'))
    let whID = response.body.data.forEach((w) => w.warehouse_inventory.forEach((wi) => {
        if (wi.product_id === pID) {
            whs.push(wi)
        }
    }))
    client.log(whs[0])
    client.global.set("warehouse_product_id_1", whs[0].product_id)
    client.global.set("first_warehouse_id", whs[0].warehouse_id)

%}

### POST Increase product stock in the specific warehouse
POST {{host}}/warehouses/increase HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "product_id": {{product_id_1}},
  "warehouse_id": {{first_warehouse_id}},
  "quantity": 10
}

> {%
    //assert status code
    client.test("test", () => {
        client.assert(response.status === 201, "code not 201")
        client.assert(response.body.code === 201, "response code is not 201")
        client.assert(response.body.message === "increase stock successfully", "response message is not 'increase stock successfully'")
    })
%}

### recheck stock
### GET Product Details
GET {{host}}/products/{{product_id_1}} HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

> {%
    let firstStock = client.global.get("product_id_1_stock")
    let expectStock = parseInt(firstStock) + 9 //after checkout
    let currentStock = parseInt(response.body.data.stock)
    client.test("test", () => {
        client.assert(response.status === 200, "code not 200")
        client.assert(response.body.code === 200, "response code is not 200")
        client.assert(response.body.message === "Success", "response message is not 'Success'")
        client.assert(expectStock === currentStock)
    })
    client.global.set("product_id_1_last_stock", response.body.data.stock)
    console.log(expectStock, currentStock);
%}

### POST Decrease product stock in the specific warehouse
POST {{host}}/warehouses/reduce HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "product_id": {{product_id_1}},
  "warehouse_id": {{first_warehouse_id}},
  "quantity": 10
}

> {%
    //assert status code
    client.test("test", () => {
        client.assert(response.status === 201, "code not 201")
        client.assert(response.body.code === 201, "response code is not 201")
        client.assert(response.body.message === "reduce stock successfully", "response message is not 'reduce stock successfully'")
    })
%}

### recheck stock
### GET Product Details
GET {{host}}/products/{{product_id_1}} HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

> {%
    let lastStock = client.global.get("product_id_1_last_stock")
    let expectStock = parseInt(lastStock) - 10
    let currentStock = parseInt(response.body.data.stock)
    client.test("test", () => {
        client.assert(response.status === 200, "code not 200")
        client.assert(response.body.code === 200, "response code is not 200")
        client.assert(response.body.message === "Success", "response message is not 'Success'")
        client.assert(expectStock === currentStock)
    })
    console.log(expectStock, currentStock);
%}

### POST Transfer product stock in the specific warehouse
POST {{host}}/warehouses/transfer HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
  "source_warehouse_id": {{warehouse_product_id_1}},
  "target_warehouse_id": {{first_warehouse_id}},
  "quantity": {{product_id_1_last_stock}},
  "product_id": {{product_id_1}}
}

> {%
    //assert status code
    client.test("test", () => {
        client.assert(response.status === 201, "code not 201")
        client.assert(response.body.code === 201, "response code is not 201")
        client.assert(response.body.message === "transfer stock successfully", "response message is not 'transfer stock successfully'")
    })
%}

#### recheck My Warehouse
#GET {{host}}/warehouses HTTP/1.1
#Content-Type: application/json
#Authorization: {{token}}
#
#> {%
#    client.test("test", () => {
#        client.assert(response.status === 200, "code not 200")
#        client.assert(response.body.code === 200, "response code is not 200")
#        client.assert(response.body.message === "Success", "response message is not 'Success'")
#        let whID = response.body.data.filter((w) => w.warehouse_inventory.filter((wi) => {
#            if (wi.product_id === client.global.get('product_id_1')) {
#                return wi
#            }
#        }))
#        client.log(whID)
#        client.global.get("warehouse_product_id_1", whID)
#        client.global.get("first_warehouse_id", response.body.data[0].id)
#    })
#%}

#### POST Change status Warehouse
#POST {{host}}/warehouses/1/status?is_active=true HTTP/1.1
#Content-Type: application/json
#Authorization: {{token}}
#
#> {%
#    //assert status code
#    client.test("test", () => {
#        client.assert(response.status === 201, "code not 201")
#        client.assert(response.body.code === 201, "response code is not 201")
#        client.assert(response.body.message === "update warehouse status successfully", "response message is not 'update warehouse status successfully'")
#    })
#%}












